export default class ActivityService {

    activities = [
        {
            id: 1,
            name: "Бассейн - малая чаша",
            location: "Бассейн",
            coach: "Иванова",
            minAge: 3,
            maxAge: 5,
            price: 300,
            startTime: "15:30",
            weekDays: [1 ,3, 5],
            eqiupment: "Плавки, очки, шапочка, шлепанцы, полотенце",
            coverImage: 'https://static3.depositphotos.com/1005383/229/i/950/depositphotos_2291225-stock-photo-swimming-pool.jpg'
        },
        {
            id: 2,
            name: "Бассейн - малая чаша",
            location: "Бассейн",
            coach: "Иванова",
            minAge: 4,
            maxAge: 6,
            price: 300,
            startTime: "16:30",
            weekDays: [1 ,3, 5],
            eqiupment: "Плавки, очки, шапочка, шлепанцы, полотенце",
            coverImage: 'https://static3.depositphotos.com/1005383/229/i/950/depositphotos_2291225-stock-photo-swimming-pool.jpg'
        },
        {
            id: 3,
            name: "Бассейн - большая чаша",
            location: "Бассейн",
            coach: "Иванова",
            minAge: 7,
            maxAge: 12,
            price: 400,
            startTime: "17:30",
            weekDays: [1 ,3, 5],
            eqiupment: "Плавки, очки, шапочка, шлепанцы, полотенце",
            coverImage: 'https://st.depositphotos.com/1000647/1271/i/950/depositphotos_12716878-stock-photo-swimming-pool.jpg'
        },
        {
            id: 4,
            name: "Бассейн - большая чаша",
            location: "Бассейн",
            coach: "Иванова",
            minAge: 12,
            maxAge: 18,
            price: 400,
            startTime: "18:30",
            weekDays: [1 ,3, 5],
            eqiupment: "Плавки, очки, шапочка, шлепанцы, полотенце",
            coverImage: 'https://st.depositphotos.com/1000647/1271/i/950/depositphotos_12716878-stock-photo-swimming-pool.jpg'
        },
        {
            id: 5,
            name: "Айкидо",
            location: "Зал единоборств",
            coach: "Петров",
            minAge: 4,
            maxAge: 6,
            price: 600,
            startTime: "9:00",
            weekDays: [2 ,4, 6],
            eqiupment: "Шорты, футболка",
            coverImage: 'https://static3.depositphotos.com/1000861/158/i/950/depositphotos_1583349-stock-photo-competition.jpg'
        },
        {
            id: 6,
            name: "Айкидо",
            location: "Зал единоборств",
            coach: "Петров",
            minAge: 7,
            maxAge: 12,
            price: 700,
            startTime: "10:00",
            weekDays: [2 ,4, 6],
            eqiupment: "Шорты, футболка",
            coverImage: 'https://st2.depositphotos.com/1003473/7283/i/950/depositphotos_72839761-stock-photo-fight-between-martial-arts-fighters.jpg'
        },
        {
            id: 7,
            name: "Айкидо",
            location: "Зал единоборств",
            coach: "Петров",
            minAge: 12,
            maxAge: 18,
            price: 800,
            startTime: "11:00",
            weekDays: [2 ,4, 6],
            eqiupment: "Шорты, футболка",
            coverImage: 'https://st2.depositphotos.com/6644020/11510/i/950/depositphotos_115107776-stock-photo-aikido-master-and-opponent.jpg'
        },
        {
            id: 8,
            name: "Бокс",
            location: "Зал единоборств",
            coach: "Викторов",
            minAge: 14,
            maxAge: 18,
            price: 1000,
            startTime: "12:30",
            weekDays: [1 ,3, 6],
            eqiupment: "Шорты, футболка, спортивная обувь, перчатки",
            coverImage: 'https://st2.depositphotos.com/1454700/6392/i/950/depositphotos_63926523-stock-photo-boxing-ring-in-arena.jpg'
        },
        {
            id: 9,
            name: "Бокс",
            location: "Зал единоборств",
            coach: "Викторов",
            minAge: 14,
            maxAge: 18,
            price: 1000,
            startTime: "12:30",
            weekDays: [2, 5],
            eqiupment: "Шорты, футболка, спортивная обувь, перчатки",
            coverImage: 'https://st2.depositphotos.com/1454700/6392/i/950/depositphotos_63926523-stock-photo-boxing-ring-in-arena.jpg'
        },
        {
            id: 10,
            name: "Бальные танцы",
            location: "Танцевальный зал",
            coach: "Викторова",
            minAge: 3,
            maxAge: 5,
            price: 800,
            startTime: "18:00",
            weekDays: [2, 4],
            eqiupment: "Шорты, футболка, чешки",
            coverImage: 'https://st.depositphotos.com/1543046/3099/v/950/depositphotos_30994533-stock-illustration-silhouettes-of-kids-dancing-ballroom.jpg'
        },
        {
            id: 11,
            name: "Бальные танцы",
            location: "Танцевальный зал",
            coach: "Викторова",
            minAge: 3,
            maxAge: 5,
            price: 800,
            startTime: "18:00",
            weekDays: [2, 4],
            eqiupment: "Шорты, футболка, чешки",
            coverImage: 'https://st.depositphotos.com/1543046/3099/v/950/depositphotos_30994533-stock-illustration-silhouettes-of-kids-dancing-ballroom.jpg'
        },
        {
            id: 12,
            name: "Современные танцы",
            location: "Танцевальный зал",
            coach: "Медведева",
            minAge: 5,
            maxAge: 7,
            price: 700,
            startTime: "16:00",
            weekDays: [3, 5],
            eqiupment: "Удобная одежда и обувь",
            coverImage: 'https://st.depositphotos.com/1026677/2059/i/950/depositphotos_20591367-stock-photo-child-dance-exercising.jpg'
        },
        {
            id: 13,
            name: "Современные танцы",
            location: "Танцевальный зал",
            coach: "Медведева",
            minAge: 7,
            maxAge: 12,
            price: 700,
            startTime: "17:00",
            weekDays: [3, 5],
            eqiupment: "Удобная одежда и обувь",
            coverImage: 'https://st.depositphotos.com/1026677/2059/i/950/depositphotos_20591367-stock-photo-child-dance-exercising.jpg'
        },
        {
            id: 14,
            name: "Современные танцы",
            location: "Танцевальный зал",
            coach: "Медведева",
            minAge: 12,
            maxAge: 18,
            price: 800,
            startTime: "18:00",
            weekDays: [3, 5],
            eqiupment: "Удобная одежда и обувь",
            coverImage: 'https://static6.depositphotos.com/1005726/559/i/950/depositphotos_5592146-stock-photo-the-dancer-jump.jpg'
        },
        {
            id: 15,
            name: "Современные танцы",
            location: "Танцевальный зал",
            coach: "Медведева",
            minAge: 12,
            maxAge: 18,
            price: 800,
            startTime: "18:00",
            weekDays: [3, 5],
            eqiupment: "Удобная одежда и обувь",
            coverImage: 'https://static6.depositphotos.com/1005726/559/i/950/depositphotos_5592146-stock-photo-the-dancer-jump.jpg'
        },
        {
            id: 16,
            name: "Современные танцы",
            location: "Танцевальный зал",
            coach: "Медведева",
            minAge: 12,
            maxAge: 18,
            price: 900,
            startTime: "9:00",
            weekDays: [6, 0],
            eqiupment: "Удобная одежда и обувь",
            coverImage: 'https://static6.depositphotos.com/1005726/559/i/950/depositphotos_5592146-stock-photo-the-dancer-jump.jpg'
        },
        {
            id: 17,
            name: "Футбол",
            location: "Футбольный стадион",
            coach: "Стрельцов",
            minAge: 4,
            maxAge: 6,
            price: 800,
            startTime: "9:00",
            weekDays: [1, 3, 5],
            eqiupment: "Удобная одежда и обувь",
            coverImage: 'https://st4.depositphotos.com/20363444/30142/i/1600/depositphotos_301423712-stock-photo-cute-boys-sportswear-playing-football.jpg'
        },
        {
            id: 18,
            name: "Футбол",
            location: "Футбольный стадион",
            coach: "Стрельцов",
            minAge: 7,
            maxAge: 12,
            price: 900,
            startTime: "11:00",
            weekDays: [1, 3, 5],
            eqiupment: "Удобная одежда и обувь",
            coverImage: 'https://st4.depositphotos.com/20363444/30142/i/1600/depositphotos_301423550-stock-photo-cute-multicultural-kids-playing-football.jpg'
        },
        {
            id: 19,
            name: "Футбол",
            location: "Футбольный стадион",
            coach: "Стрельцов",
            minAge: 12,
            maxAge: 18,
            price: 1000,
            startTime: "13:00",
            weekDays: [1, 3, 5],
            eqiupment: "Удобная одежда и обувь",
            coverImage: 'https://st.depositphotos.com/1162190/1951/i/950/depositphotos_19511151-stock-photo-green-soccer-field.jpg'
        },
        {
            id: 20,
            name: "Футбол",
            location: "Футбольный стадион",
            coach: "Стрельцов",
            minAge: 12,
            maxAge: 18,
            price: 1000,
            startTime: "10:00",
            weekDays: [6, 0],
            eqiupment: "Удобная одежда и обувь",
            coverImage: 'https://st.depositphotos.com/1162190/1951/i/950/depositphotos_19511151-stock-photo-green-soccer-field.jpg'
        },
        {
            id: 21,
            name: "Баскетбол",
            location: "Зал номер 1",
            coach: "Сидоров",
            minAge: 7,
            maxAge: 12,
            price: 500,
            startTime: "10:00",
            weekDays: [2, 4, 6],
            eqiupment: "Удобная одежда и обувь",
            coverImage: 'https://st.depositphotos.com/1028911/4991/i/950/depositphotos_49918331-stock-photo-basketball-court-floor-with-ball.jpg'
        },
        {
            id: 22,
            name: "Баскетбол",
            location: "Зал номер 1",
            coach: "Сидоров",
            minAge: 12,
            maxAge: 18,
            price: 600,
            startTime: "11:30",
            weekDays: [2, 4, 6],
            eqiupment: "Удобная одежда и обувь",
            coverImage: 'https://st.depositphotos.com/1028911/4991/i/950/depositphotos_49918331-stock-photo-basketball-court-floor-with-ball.jpg'
        },
        {
            id: 23,
            name: "Баскетбол",
            location: "Зал номер 1",
            coach: "Сидоров",
            minAge: 12,
            maxAge: 18,
            price: 600,
            startTime: "10:00",
            weekDays: [1, 3, 5],
            eqiupment: "Удобная одежда и обувь",
            coverImage: 'https://st.depositphotos.com/1028911/4991/i/950/depositphotos_49918331-stock-photo-basketball-court-floor-with-ball.jpg'
        },
        {
            id: 24,
            name: "Воллейбол",
            location: "Зал номер 2",
            coach: "Зубов",
            minAge: 7,
            maxAge: 12,
            price: 400,
            startTime: "10:00",
            weekDays: [1, 3, 5],
            eqiupment: "Удобная одежда и обувь",
            coverImage: 'https://st2.depositphotos.com/1018611/7738/i/950/depositphotos_77386318-stock-photo-teenagers-play-volleyball-game.jpg'
        },
        {
            id: 25,
            name: "Воллейбол",
            location: "Зал номер 2",
            coach: "Зубов",
            minAge: 12,
            maxAge: 18,
            price: 500,
            startTime: "11:00",
            weekDays: [1, 3, 5],
            eqiupment: "Удобная одежда и обувь",
            coverImage: 'https://st2.depositphotos.com/1018611/7738/i/950/depositphotos_77386318-stock-photo-teenagers-play-volleyball-game.jpg'
        },
        {
            id: 26,
            name: "Воллейбол",
            location: "Зал номер 2",
            coach: "Зубов",
            minAge: 12,
            maxAge: 18,
            price: 500,
            startTime: "11:00",
            weekDays: [6, 0],
            eqiupment: "Удобная одежда и обувь",
            coverImage: 'https://st2.depositphotos.com/1018611/7738/i/950/depositphotos_77386318-stock-photo-teenagers-play-volleyball-game.jpg'
        }
    ];


    getActivities = () => {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve(this.activities);
                reject(new Error('Ошибка при получении данных'));
            }, 2000)
        });
    }
}